# This includes configuration to run the integration test suite.
# Mounts the test artifacts folder, and includes selenium browser

version: '3.9'

services:

  app:
    image: ${IMG_REG_REPO}/app:${IMG_HEAD_SHA}
    environment:
      TESTS_ARTIFACTS_DIR: /tests_artifacts
    # mount the test artifacts folder to share screenshots
    volumes:
      - ../tests_artifacts:/tests_artifacts

  # selenium browser used for integration tests
  selenium_chrome:
    image: selenium/standalone-chrome:107.0.5304.87-20221104
    ports:
      - 7900:7900
    environment:
      SE_VNC_NO_PASSWORD: 1

  worker_wrapper:
    image: ${IMG_REG_REPO}/worker_wrapper:${IMG_HEAD_SHA}

  qgis:
    image: ${IMG_REG_REPO}/qgis:${IMG_HEAD_SHA}

  redis:
    image: ${IMG_REG_REPO}/redis:${IMG_HEAD_SHA}
